baseURL: /
title: The Blogging of Isaac
theme: hugo-theme-bootstrap
copyright: "Copyright © 2021-{year} Isaac Yip. All Rights Reserved."
defaultContentLanguage: zh-hk
hasCJKLanguage: true # Uncomment it if your content contains Chinese/Japanese/Korean Languages.
# defaultContentLanguageInSubdir: true
# disableLanguages:
#  - fr
#  - zh-cn
#  - zh-tw
paginate: 10
# paginatePath: page
enableRobotsTXT: true
enableEmoji: true
pygmentsUseClasses: true
# googleAnalytics: UA-123-45
# disqusShortname: yourdiscussshortname

blackfriday:
  hrefTargetBlank: true

taxonomies:
  tag: tags
  # category: categories
  # series: series
  # authors: authors

build:
  writeStats: true
# permalinks:
#   news: /news/:year/:month/:title/

# module:
#   proxy: https://goproxy.cn
