zh-hk:
  languageName: "繁體中文"
  weight: 1
  params:
    dateFormat: '2006-01-02'
    # description: 一个快速、响应式和功能丰富的 Hugo 博客主题
    keywords: 'Hugo, Bootstrap, Blog'
    archive:
      dateFormat: 01-02
