email: "yip102011@gmail.com"
# facebook: yourfacebookusername
github: "yip102011"
# gitlab: yourgitlabusername
linkedin: "in/isaac-yip-1bb738b8/"
# xing: yourxingusername
stackoverflow: "2854252"
# twitter: yourtwitterusername
# weibo: yourweibousername
# zhihu: yourzhihuusername
# instagram: yourinstagramusername
# quora: yourquorausername
# tumblr: yourtumblrusername
# reddit: yourredditusername
# telegram: yourtelegramusername
# qq: yourqqnumber
# dockerhub: yourdockerhubusername
# bitbucket: yourbitbucketworkspaceid
# kaggle: yourkaggleusername
# medium: yourmediumusername # Medium username or custom domain(e.g. https://custom.domain.tld).
# lastfm: yourlastfmusername
# bilibili: yourbilibiliuserid
# youtube: youryoutubechannelid
# discord: yourdiscordinvitecode
# discourse: https://yourforum.tld
# facebookgroup: yourfacebookgroupname
# tiktok: yourtiktokusername
# pinterest: yourpinterestusername
# mastodon: yourmastodonusername
# liberapay: yourliberapayaccount
# paypal: razonyang
# patreon: razonyang
# tipeee: yourtipeeeaccount-fr
